# site settings
title: Sunjin David Kim
subtitle: Data Analyst
email: sjdkim0412@gmail.com
description: A site dedicated to Data Science, created by David Kim.
baseurl: "/david_data_science" # the subpath of your site, e.g. /blog
url: https://davidsjk.github.io # the base hostname & protocol for your site
author: Sunjin David Kim
street_address:
city:
state:
zip_code:
country: United States of America
phone: (714) 321-4583

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/davidsjk
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/davidsjk
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
